export * from './adCreative.service';
import { AdCreativeService } from './adCreative.service';
export * from './adCreativeProfile.service';
import { AdCreativeProfileService } from './adCreativeProfile.service';
export * from './brandprofile.service';
import { BrandprofileService } from './brandprofile.service';
export * from './campaign.service';
import { CampaignService } from './campaign.service';
export * from './campaignDeliverable.service';
import { CampaignDeliverableService } from './campaignDeliverable.service';
export * from './campaignInfluencer.service';
import { CampaignInfluencerService } from './campaignInfluencer.service';
export * from './campaignInfluencerPost.service';
import { CampaignInfluencerPostService } from './campaignInfluencerPost.service';
export * from './comments.service';
import { CommentsService } from './comments.service';
export * from './digitalMarketing.service';
import { DigitalMarketingService } from './digitalMarketing.service';
export * from './influencerProfiles.service';
import { InfluencerProfilesService } from './influencerProfiles.service';
export * from './invitations.service';
import { InvitationsService } from './invitations.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './postMetrics.service';
import { PostMetricsService } from './postMetrics.service';
export * from './posts.service';
import { PostsService } from './posts.service';
export * from './sharing.service';
import { SharingService } from './sharing.service';
export * from './socialMediaService.service';
import { SocialMediaServiceService } from './socialMediaService.service';
export * from './statistics.service';
import { StatisticsService } from './statistics.service';
export * from './subscriptionPlansAdmin.service';
import { SubscriptionPlansAdminService } from './subscriptionPlansAdmin.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './userMediaData.service';
import { UserMediaDataService } from './userMediaData.service';
export * from './userSubscriptions.service';
import { UserSubscriptionsService } from './userSubscriptions.service';
export * from './utility.service';
import { UtilityService } from './utility.service';
export * from './wallet.service';
import { WalletService } from './wallet.service';
export const APIS = [AdCreativeService, AdCreativeProfileService, BrandprofileService, CampaignService, CampaignDeliverableService, CampaignInfluencerService, CampaignInfluencerPostService, CommentsService, DigitalMarketingService, InfluencerProfilesService, InvitationsService, NotificationsService, PostMetricsService, PostsService, SharingService, SocialMediaServiceService, StatisticsService, SubscriptionPlansAdminService, TransactionsService, UserService, UserMediaDataService, UserSubscriptionsService, UtilityService, WalletService];
