/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CampaignTier { 
    /**
     * Unique identifier for the entity
     */
    id?: number;
    /**
     * UUID for the campaign tier
     */
    uuid: string;
    /**
     * Name of the campaign tier
     */
    name: string;
    /**
     * Minimum followers required for the tier
     */
    min_followers: number;
    /**
     * Maximum followers allowed for the tier (null for no limit)
     */
    max_followers: number;
    /**
     * Amount to be paid per post for this tier
     */
    amount_per_post: number;
    /**
     * Currency for the payment amount
     */
    currency: string;
}

