/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostMetrics } from './postMetrics';
import { CampaignInfluencer } from './campaignInfluencer';


export interface CampaignInfluencerPost { 
    /**
     * Unique identifier for the entity
     */
    id?: number;
    /**
     * Ties the post to influencer + campaign
     */
    campaignInfluencer?: CampaignInfluencer;
    /**
     * \"Skincare Routine\"
     */
    title?: string;
    content_type?: CampaignInfluencerPost.ContentTypeEnum;
    platform?: CampaignInfluencerPost.PlatformEnum;
    /**
     * The \"View post\" link (set on publish)
     */
    post_url?: string;
    /**
     * Set on publish
     */
    published_at?: string;
    status?: CampaignInfluencerPost.StatusEnum;
    /**
     * Payout for this post
     */
    payout_amount?: number;
    payment_status?: CampaignInfluencerPost.PaymentStatusEnum;
    /**
     * Null until paid
     */
    paid_at?: string;
    thumbnail_url?: string;
    metrics?: Array<PostMetrics>;
}
export namespace CampaignInfluencerPost {
    export const ContentTypeEnum = {
        Reel: 'reel',
        Story: 'story',
        Post: 'post',
        Video: 'video',
    } as const;
    export type ContentTypeEnum = typeof ContentTypeEnum[keyof typeof ContentTypeEnum];
    export const PlatformEnum = {
        Instagram: 'instagram',
        Tiktok: 'tiktok',
        Youtube: 'youtube',
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
    export const StatusEnum = {
        Pending: 'pending',
        Submitted: 'submitted',
        Approved: 'approved',
        Published: 'published',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const PaymentStatusEnum = {
        Pending: 'pending',
        Paid: 'paid',
    } as const;
    export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];
}


