/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CampaignStatsResponse { 
    campaign?: object;
    reach?: number;
    interactions?: number;
    engagementRate?: number;
    breakdown?: object;
    posts?: Array<string>;
}

