/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignOffer } from './campaignOffer';


export interface CampaignOfferLine { 
    /**
     * Unique identifier for the entity
     */
    id?: number;
    offer?: CampaignOffer;
    title?: string;
    /**
     * Work details for non-content lines
     */
    description?: string;
    content_type?: CampaignOfferLine.ContentTypeEnum;
    platform?: CampaignOfferLine.PlatformEnum;
    quantity?: number;
    /**
     * Per-unit rate (content) or flat cost (chore)
     */
    rate?: number;
    due_date?: string;
}
export namespace CampaignOfferLine {
    export const ContentTypeEnum = {
        Reel: 'reel',
        Story: 'story',
        Post: 'post',
        Video: 'video',
    } as const;
    export type ContentTypeEnum = typeof ContentTypeEnum[keyof typeof ContentTypeEnum];
    export const PlatformEnum = {
        Instagram: 'instagram',
        Tiktok: 'tiktok',
        Youtube: 'youtube',
        Facebook: 'facebook',
        X: 'x',
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
}


