/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CampaignSharesResponse { 
    campaignId?: number;
    campaignName?: string;
    total?: number;
    active?: number;
    completed?: number;
    rejected?: number;
    flagged?: number;
    reviewed?: number;
    influencers?: number;
    paidOut?: number;
    byStatus?: object;
}

