/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignOfferLine } from './campaignOfferLine';
import { CampaignInfluencer } from './campaignInfluencer';


export interface CampaignOffer { 
    /**
     * Unique identifier for the entity
     */
    id?: number;
    campaignInfluencer?: CampaignInfluencer;
    /**
     * 1, 2, 3… per assignment
     */
    round?: number;
    proposed_by?: CampaignOffer.ProposedByEnum;
    message?: string;
    expires_at?: string;
    status?: CampaignOffer.StatusEnum;
    responded_at?: string;
    /**
     * Post-signature change order
     */
    is_amendment?: boolean;
    lines?: Array<CampaignOfferLine>;
}
export namespace CampaignOffer {
    export const ProposedByEnum = {
        Brand: 'brand',
        Influencer: 'influencer',
    } as const;
    export type ProposedByEnum = typeof ProposedByEnum[keyof typeof ProposedByEnum];
    export const StatusEnum = {
        Proposed: 'proposed',
        Accepted: 'accepted',
        Declined: 'declined',
        Superseded: 'superseded',
        Expired: 'expired',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


