/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Campaign } from './campaign';


export interface CampaignDeliverable { 
    /**
     * Unique identifier for the entity
     */
    id?: number;
    /**
     * Campaign these outputs belong to
     */
    campaign?: Campaign;
    content_type?: CampaignDeliverable.ContentTypeEnum;
    platform?: CampaignDeliverable.PlatformEnum;
    /**
     * Number of posts required
     */
    quantity?: number;
    /**
     * Guide amount per post
     */
    rate_per_post?: number;
    /**
     * When these outputs are due (from negotiation)
     */
    due_date?: string;
}
export namespace CampaignDeliverable {
    export const ContentTypeEnum = {
        Reel: 'reel',
        Story: 'story',
        Post: 'post',
        Video: 'video',
    } as const;
    export type ContentTypeEnum = typeof ContentTypeEnum[keyof typeof ContentTypeEnum];
    export const PlatformEnum = {
        Instagram: 'instagram',
        Tiktok: 'tiktok',
        Youtube: 'youtube',
        Facebook: 'facebook',
        X: 'x',
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
}


