/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserDto { 
    user_name?: string;
    phone_number?: string;
    email?: string;
    password?: string;
    first_name?: string;
    last_name?: string;
    profileType?: CreateUserDto.ProfileTypeEnum;
}
export namespace CreateUserDto {
    export const ProfileTypeEnum = {
        Brand: 'brand',
        Influencer: 'influencer',
        Both: 'both',
    } as const;
    export type ProfileTypeEnum = typeof ProfileTypeEnum[keyof typeof ProfileTypeEnum];
}


