/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCampaignInfluencerPostDto { 
    /**
     * Parent CampaignInfluencer ID
     */
    campaignInfluencerId: number;
    title?: string;
    content_type: CreateCampaignInfluencerPostDto.ContentTypeEnum;
    platform: CreateCampaignInfluencerPostDto.PlatformEnum;
    /**
     * The \"View post\" link
     */
    post_url?: string;
    status?: CreateCampaignInfluencerPostDto.StatusEnum;
    /**
     * Payout for this post
     */
    payout_amount?: number;
    payment_status?: CreateCampaignInfluencerPostDto.PaymentStatusEnum;
    thumbnail_url?: string;
}
export namespace CreateCampaignInfluencerPostDto {
    export const ContentTypeEnum = {
        Reel: 'reel',
        Story: 'story',
        Post: 'post',
        Video: 'video',
    } as const;
    export type ContentTypeEnum = typeof ContentTypeEnum[keyof typeof ContentTypeEnum];
    export const PlatformEnum = {
        Instagram: 'instagram',
        Tiktok: 'tiktok',
        Youtube: 'youtube',
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
    export const StatusEnum = {
        Pending: 'pending',
        Submitted: 'submitted',
        Approved: 'approved',
        Published: 'published',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const PaymentStatusEnum = {
        Pending: 'pending',
        Paid: 'paid',
    } as const;
    export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];
}


