/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CampaignTier } from './campaignTier';


export interface CreateCampaignDto { 
    /**
     * Name of the campaign
     */
    name: string;
    /**
     * Platforms for the campaign
     */
    platforms?: Array<string>;
    /**
     * Access type for the campaign
     */
    access?: string;
    /**
     * ID of the user who created the campaign
     */
    creator_id: number;
    /**
     * Link associated with the campaign
     */
    link?: string;
    /**
     * Detailed description of the campaign
     */
    description?: string;
    /**
     * Start date of the campaign
     */
    start_date?: string;
    /**
     * End date of the campaign
     */
    end_date?: string;
    /**
     * Generate Ai captions for the campaign
     */
    auto_generate_captions?: boolean;
    /**
     * Hash tags for the campaign
     */
    hash_tags?: Array<string>;
    /**
     * Package associated with the campaign
     */
    'package': string;
    /**
     * Flag to indicate if a post should be generated for the campaign
     */
    generate_post?: boolean;
    /**
     * Array of file URLs associated with the campaign
     */
    files?: Array<string>;
    /**
     * Array of campaign tiers associated with the campaign
     */
    campaignTier?: Array<CampaignTier>;
}

