/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateBenefitDto } from './createBenefitDto';


export interface CreateSubscriptionDto { 
    /**
     * Name of the subscription plan
     */
    name: string;
    /**
     * Price of the subscription plan
     */
    price: number;
    /**
     * Currency of the subscription plan
     */
    currency: string;
    /**
     * Billing cycle of the subscription plan
     */
    billingCycle: string;
    benefit: CreateBenefitDto;
}

