/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserSubscriptionDto { 
    /**
     * The ID of the user who is subscribing
     */
    userId: number;
    /**
     * The ID of the subscription plan to subscribe to
     */
    subscriptionPlanId: number;
    /**
     * The start date of the subscription
     */
    startDate: string;
}

