/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCampaignDeliverableDto { 
    /**
     * Parent CampaignInfluencer ID
     */
    campaignInfluencerId: number;
    content_type: CreateCampaignDeliverableDto.ContentTypeEnum;
    platform: CreateCampaignDeliverableDto.PlatformEnum;
    /**
     * Number of posts agreed
     */
    quantity?: number;
    /**
     * Amount per post
     */
    rate_per_post?: number;
}
export namespace CreateCampaignDeliverableDto {
    export const ContentTypeEnum = {
        Reel: 'reel',
        Story: 'story',
        Post: 'post',
        Video: 'video',
    } as const;
    export type ContentTypeEnum = typeof ContentTypeEnum[keyof typeof ContentTypeEnum];
    export const PlatformEnum = {
        Instagram: 'instagram',
        Tiktok: 'tiktok',
        Youtube: 'youtube',
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
}


