/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateWalletDto { 
    userId?: number;
    trendor_id: string;
    balance: number;
    frozen: boolean;
    withdrawalLockedUntil: string;
    currency?: string;
}

