/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCreativeProfileDto { 
    /**
     * The ID of the user this profile belongs to.
     */
    userId: number;
    /**
     * A brief bio for the creative professional.
     */
    bio?: string;
    /**
     * Link to the creative\'s portfolio.
     */
    portfolioUrl?: string;
    /**
     * List of the creative\'s skills.
     */
    skills?: Array<string>;
}

