/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateBenefitDto { 
    /**
     * Number of free posts included in the plan
     */
    freePosts: number;
    /**
     * Price for additional posts beyond the free limit
     */
    extraPostsPrice: number;
    /**
     * Whether the plan includes visibility boosting features
     */
    boostVisibility: boolean;
    /**
     * Whether the plan includes priority customer support
     */
    prioritySupport: boolean;
    /**
     * Whether the plan includes access to analytics
     */
    analyticsAccess: boolean;
    /**
     * Whether the plan allows unlimited posts
     */
    unlimitedPosts: boolean;
    /**
     * Whether the plan includes a dedicated account manager
     */
    dedicatedManager: boolean;
    /**
     * Whether the plan allows custom hashtags
     */
    customHashtags: boolean;
    /**
     * Whether the plan includes cross-platform boosting
     */
    crossPlatformBoost: boolean;
}

