/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateNotificationDto { 
    userId: number;
    trendorId: string;
    type: CreateNotificationDto.TypeEnum;
    message: string;
    isRead: boolean;
    targetId: number;
    targetType: CreateNotificationDto.TargetTypeEnum;
}
export namespace CreateNotificationDto {
    export const TypeEnum = {
        InvitationReceived: 'INVITATION RECEIVED',
        InvitationAccepted: 'INVITATION ACCEPTED',
        InvitationDeclined: 'INVITATION DECLINED',
        PostLiked: 'POST LIKED',
        PostCommented: 'POST COMMENTED',
        AccountNumberUpdated: 'ACCOUNT_NUMBER_UPDATED',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const TargetTypeEnum = {
        Post: 'POST',
        Comment: 'COMMENT',
        User: 'USER',
        Other: 'OTHER',
        Wallet: 'WALLET',
    } as const;
    export type TargetTypeEnum = typeof TargetTypeEnum[keyof typeof TargetTypeEnum];
}


