/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAdCreativeDto { 
    /**
     * The ID of the creative profile who created this.
     */
    creativeProfileId?: number;
    /**
     * The name of the concept
     */
    conceptName: string;
    /**
     * The type of asset (image, video)
     */
    assetType: string;
    /**
     * The contact of the creative team
     */
    creativeTeamContact?: string;
}

