/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDigitalMarketingDto { 
    /**
     * The ID of the user
     */
    userId: number;
    /**
     * Professional healine
     */
    professionalHeadline?: string;
    /**
     * About Me / Bio
     */
    bio?: string;
    /**
     * Location (City, Country)
     */
    location?: string;
    /**
     * Personal website or Portfolio link
     */
    website?: string;
    /**
     * LinkedIn profile link
     */
    linkedInProfileLink?: string;
    /**
     * Digital Marketing Specialization
     */
    digitalMarketingSpecializations?: Array<string>;
    /**
     * Tools & Platforms Proficiency
     */
    Proficiency?: Array<string>;
    /**
     * Industry Specialization
     */
    industrySpecialization?: Array<string>;
    /**
     * Languages (if applicable)
     */
    languages?: Array<string>;
    /**
     * Years of Experience
     */
    experience?: Array<string>;
    /**
     * Portfolio/Case Study Links
     */
    portfolioCaseStudyLinks?: string;
    /**
     * Availability
     */
    availability?: Array<string>;
    /**
     * Preferred Project Types
     */
    preferredProjectTypes?: Array<string>;
    /**
     * Pricing Model
     */
    pricingModel?: Array<string>;
    /**
     * Estimated Rate/Budget
     */
    estimatedRate?: string;
    /**
     * Education
     */
    education?: string;
    /**
     * Certifications
     */
    certifications?: Array<string>;
}

