/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateBrandprofileDto { 
    userId: number;
    brand_name?: string;
    contact_name?: string;
    industry?: string;
    website?: string;
}

