/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreativeProfile { 
    /**
     * First name of the creative profile
     */
    first_name?: string;
    /**
     * Last name of the creative profile
     */
    last_name?: string;
    /**
     * Bio of the creative profile
     */
    bio?: string;
    /**
     * Portfolio URL of the creative profile
     */
    portfolioUrl?: string;
    /**
     * Skills of the creative profile
     */
    skills?: Array<string>;
}

