/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DebitWalletDto { 
    trendorsId: string;
    amount: number;
    currency: DebitWalletDto.CurrencyEnum;
}
export namespace DebitWalletDto {
    export const CurrencyEnum = {
        Usd: 'USD',
        Eur: 'EUR',
        Gbp: 'GBP',
        Ngn: 'NGN',
    } as const;
    export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];
}


