/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FetchPostDto { 
    order?: FetchPostDto.OrderEnum;
    filter?: object;
    /**
     * This initiates a search when present
     */
    searchString?: string;
    /**
     * This initiates a search when present
     */
    limit?: number;
    /**
     * This initiates a search when present
     */
    page?: number;
    /**
     * Filter posts by campaign type
     */
    campaignType?: FetchPostDto.CampaignTypeEnum;
    /**
     * This initiates a search when present
     */
    relations?: Array<string>;
}
export namespace FetchPostDto {
    export const OrderEnum = {
        Asc: 'ASC',
        Desc: 'DESC',
    } as const;
    export type OrderEnum = typeof OrderEnum[keyof typeof OrderEnum];
    export const CampaignTypeEnum = {
        Open: 'open',
        InviteOnly: 'invite_only',
        Application: 'application',
    } as const;
    export type CampaignTypeEnum = typeof CampaignTypeEnum[keyof typeof CampaignTypeEnum];
}


