/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FetchPostDto { 
    order?: FetchPostDto.OrderEnum;
    filter?: object;
    /**
     * This initiates a search when present
     */
    searchString?: string;
    /**
     * This initiates a search when present
     */
    limit?: number;
    /**
     * This initiates a search when present
     */
    page?: number;
    /**
     * This initiates a search when present
     */
    relations?: Array<string>;
}
export namespace FetchPostDto {
    export const OrderEnum = {
        Asc: 'ASC',
        Desc: 'DESC',
    } as const;
    export type OrderEnum = typeof OrderEnum[keyof typeof OrderEnum];
}


