/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FindTransactionDto { 
    limit?: number;
    page?: number;
    sort?: FindTransactionDto.SortEnum;
    searchQuery?: string;
    trendor_id: string;
    transaction_type?: FindTransactionDto.TransactionTypeEnum;
}
export namespace FindTransactionDto {
    export const SortEnum = {
        Asc: 'ASC',
        Desc: 'DESC',
    } as const;
    export type SortEnum = typeof SortEnum[keyof typeof SortEnum];
    export const TransactionTypeEnum = {
        Credit: 'credit',
        Debit: 'debit',
        All: 'all',
    } as const;
    export type TransactionTypeEnum = typeof TransactionTypeEnum[keyof typeof TransactionTypeEnum];
}


