/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvitationFilterOptions { 
    userId?: number;
    limit?: number;
    page?: number;
    sort?: string;
    searchQuery?: string;
}

