/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoadMoreOptions } from './loadMoreOptions';


export interface LoadMoreDto { 
    order?: LoadMoreDto.OrderEnum;
    loadMoreOptions?: LoadMoreOptions;
    /**
     * This initiates a search when present
     */
    searchString?: string;
    /**
     * This initiates a search when present
     */
    limit?: number;
    /**
     * This initiates a search when present
     */
    relations?: Array<string>;
}
export namespace LoadMoreDto {
    export const OrderEnum = {
        Asc: 'ASC',
        Desc: 'DESC',
    } as const;
    export type OrderEnum = typeof OrderEnum[keyof typeof OrderEnum];
}


