/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoadMoreOptions { 
    type: LoadMoreOptions.TypeEnum;
    id: number;
}
export namespace LoadMoreOptions {
    export const TypeEnum = {
        Gt: 'GT',
        Lt: 'LT',
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


