/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OfferLineDto { 
    /**
     * Required when content_type is null (chore work)
     */
    title?: string;
    description?: string;
    content_type?: OfferLineDto.ContentTypeEnum;
    platform?: OfferLineDto.PlatformEnum;
    quantity?: number;
    /**
     * Per-unit rate, or flat cost for chores
     */
    rate?: number;
    due_date?: string;
}
export namespace OfferLineDto {
    export const ContentTypeEnum = {
        Reel: 'reel',
        Story: 'story',
        Post: 'post',
        Video: 'video',
    } as const;
    export type ContentTypeEnum = typeof ContentTypeEnum[keyof typeof ContentTypeEnum];
    export const PlatformEnum = {
        Instagram: 'instagram',
        Tiktok: 'tiktok',
        Youtube: 'youtube',
        Facebook: 'facebook',
        X: 'x',
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
}


