/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaginationDataDto { 
    /**
     * The list of items
     */
    list: Array<Array<string>>;
    /**
     * Total number of items available
     */
    count: number;
    /**
     * Current page number
     */
    page: number;
}

