/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginationDataDto } from './paginationDataDto';


export interface PaginatedResponseDto { 
    error: boolean;
    message: string;
    data?: PaginationDataDto;
}

