/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PayFromWalletDto { 
    /**
     * Payer trendors ID
     */
    trendorsId: string;
    /**
     * Amount to deduct (must be greater than zero)
     */
    amount: number;
    /**
     * What the payment is for
     */
    description?: string;
}

