/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecordPostMetricsDto { 
    /**
     * CampaignInfluencerPost ID being measured
     */
    campaignInfluencerPostId: number;
    views?: number;
    likes?: number;
    comments?: number;
    shares?: number;
}

