/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResetPasswordDto { 
    /**
     * The password reset token received by the user.
     */
    token: string;
    /**
     * New password for the user
     */
    newPassword: string;
}

