/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RespondToInvitationDto { 
    /**
     * The response to the invitation.
     */
    status: RespondToInvitationDto.StatusEnum;
}
export namespace RespondToInvitationDto {
    export const StatusEnum = {
        Accepted: 'Accepted',
        Declined: 'Declined',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


