/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RespondCampaignOfferDto { 
    /**
     * accepted | declined | expired
     */
    status?: RespondCampaignOfferDto.StatusEnum;
    message?: string;
}
export namespace RespondCampaignOfferDto {
    export const StatusEnum = {
        Proposed: 'proposed',
        Accepted: 'accepted',
        Declined: 'declined',
        Superseded: 'superseded',
        Expired: 'expired',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


