/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCampaignDeliverableDto { 
    /**
     * Number of posts agreed
     */
    quantity?: number;
    /**
     * Amount per post
     */
    rate_per_post?: number;
}

