/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Campaign } from './campaign';


export interface UpdatePostDto { 
    /**
     * same as description when being used as a campaign
     */
    text?: string;
    heading?: string;
    link?: string;
    generate_ai_rewrite?: boolean;
    trendorsId?: string;
    userName?: string;
    userId?: number;
    channel?: string;
    url?: string;
    images?: Array<string>;
    srcUrl?: string;
    srcName?: string;
    srcImgUrl?: string;
    isSponsored?: boolean;
    cost?: number;
    incentiveShareCount?: number;
    maxIncentiveShares?: number;
    /**
     * Campaign this post belongs to
     */
    campaign?: Campaign;
    id?: number;
    createdAt?: string;
    likes?: Array<string>;
    shares?: Array<string>;
    comments?: Array<string>;
}

