/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreativeProfile } from './creativeProfile';
import { Wallet } from './wallet';
import { CampaignInfluencer } from './campaignInfluencer';
import { BrandProfile } from './brandProfile';


export interface UpdateUserDto { 
    /**
     * Unique identifier for the entity
     */
    id?: number;
    first_name?: string;
    last_name?: string;
    user_name?: string;
    trendors_id?: string;
    phone_number?: string;
    email?: string;
    password?: string;
    passwordResetToken?: string;
    passwordResetExpires?: string;
    isActive?: boolean;
    twitter_handle?: string;
    twitter_image?: string;
    facebook_username?: string;
    instagram_handle?: string;
    paystackRecipientCode?: string;
    posts?: Array<string>;
    comments?: Array<string>;
    users_media_data?: Array<string>;
    influncerProfile?: object;
    digitalMarketing?: object;
    userSubscriptions?: Array<string>;
    creativeProfile?: CreativeProfile;
    invitations?: Array<string>;
    createdCampaigns?: Array<string>;
    brandProfile?: BrandProfile;
    notifications?: Array<string>;
    wallet?: Wallet;
    campaignInfluencers?: Array<CampaignInfluencer>;
}

