/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserMediaDatumDto { 
    user_name?: string;
    social_media_name?: string;
    followers_count?: number;
    verified?: boolean;
    userId?: number;
}

