/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateAdCreativeDto { 
    /**
     * The ID of the creative profile who created this.
     */
    creativeProfileId?: number;
    /**
     * The name of the concept
     */
    conceptName?: string;
    /**
     * The type of asset (image, video)
     */
    assetType?: string;
    /**
     * The contact of the creative team
     */
    creativeTeamContact?: string;
    /**
     * Update the status of the creative.
     */
    status?: UpdateAdCreativeDto.StatusEnum;
    /**
     * Set to true when the client gives final sign-off.
     */
    isApprovedByClient?: boolean;
}
export namespace UpdateAdCreativeDto {
    export const StatusEnum = {
        Draft: 'Draft',
        SubmittedForReview: 'Submitted For Review',
        Approved: 'Approved',
        Rejected: 'Rejected',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


