/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCampaignInfluencerPostDto { 
    title?: string;
    /**
     * The \"View post\" link
     */
    post_url?: string;
    status?: UpdateCampaignInfluencerPostDto.StatusEnum;
    /**
     * Publish date (ISO); auto-set on publish
     */
    published_at?: string;
    /**
     * Payout for this post
     */
    payout_amount?: number;
    payment_status?: UpdateCampaignInfluencerPostDto.PaymentStatusEnum;
    thumbnail_url?: string;
}
export namespace UpdateCampaignInfluencerPostDto {
    export const StatusEnum = {
        Pending: 'pending',
        Submitted: 'submitted',
        Approved: 'approved',
        Published: 'published',
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const PaymentStatusEnum = {
        Pending: 'pending',
        Paid: 'paid',
    } as const;
    export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];
}


