/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateSharingDto { 
    postId?: number;
    sharers_trendorsId?: string;
    sharers_userId?: string;
    external_post_id?: string;
    external_post_url?: string;
    tracking_code?: string;
    deviceId?: string;
    ipAddress?: string;
    rewardAmount?: number;
    status?: string;
    social_media?: string;
    paid?: boolean;
}

