/**
 * Trendors
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateInfluncerProfileDto { 
    /**
     * The ID of the user
     */
    userId?: number;
    /**
     * Professional healine / niche
     */
    professionalHeadline?: string;
    /**
     * About Me / Bio
     */
    bio?: string;
    /**
     * Location (City, Country)
     */
    location?: string;
    /**
     * Personal website or blog link
     */
    website?: string;
    /**
     * Link for the media kit (optional)
     */
    mediaKitLink?: string;
    /**
     * Primary social media Platforms
     */
    primaryPlatforms?: Array<string>;
    /**
     * Instagram handle
     */
    instagramHandle?: string;
    /**
     * YouTube channel link
     */
    youtubeChannelLink?: string;
    /**
     * TikTok profile link
     */
    tiktokProfileLink?: string;
    /**
     * Other social media links 
     */
    otherSocialMediaLinks?: Array<string>;
    /**
     * Content Niches / Categories
     */
    contentNiches?: Array<string>;
    /**
     * Audience gender split
     */
    audienceGenderSplit?: string;
    /**
     * Audience age range
     */
    audienceAgeRange?: string;
    /**
     * Top audience location
     */
    topAudienceLocations?: Array<string>;
    /**
     * Average engagement rate
     */
    averageEngagementRate?: string;
    /**
     * Types of collaborations open to
     */
    collaborationTypes?: Array<string>;
    /**
     * Post collaborations (Brands/Campaigns)
     */
    pastCollaborations?: string;
    /**
     * Pricing models
     */
    pricingModels?: Array<string>;
    /**
     * Estaimated rates
     */
    estimatedRates?: string;
    /**
     * Availability status
     */
    availability?: Array<string>;
}

